### ISSUE TITLE
Implement healthcheck, discussion

### ISSUE THREAD

**Issue by ThomDietrich** [djmaze/resticker#42] opened 2020-06-14 09:26 UTC
Hey all,

Related to #37 but going beyond.

A backup could fail at any given time. Reasons could be temporary (e.g. networking issues or storage space) or permanent (e.g. origin or destination details changed).
In order to both detect issues but to also be able to recover in one of the following cron-slots we should implement a docker healthcheck. The following assumes that our shared understanding of health is "Backups are successfully and continuously performed according to the given cron schedule".

Possible solutions:

* Check for the availability of the destination (just as in #37). Doesn't cover all possible errors, does not cover origin errors.

* Check whether individual backups succeeded. As the healthcheck is independently defined from the rest of the image, we need a proxy to indicate health. I suggest to store the exit code of restic (e.g. `echo $? > /restic-backup-exit-code`), which then can be evaluated by a healthcheck command, or alternatively create a flag conditionally (e.g. `touch /restic-backup/failed`).
  Potential issues:
  * Restics exit codes are not quite consistent. Imho not a big issue as for the purpose of a healthcheck everything other than 0 is probably worth being aware of.
  * As users can define their execution interval via the BACKUP_CRON variable we are not able to define interval and retries for the healthcheck. The solution would need to switch to unhealthy state as soon as one backup did not succeed. This is fine for most setups, might be an issue for swarm setups.
  * Workaround: Swarm users and power-users with special use case can redefine their healthcheck in `docker-compose.yml`
  * Workaround 2: The number of consecutive fails can be counted (e.g. `echo $? >> /restic-backup-exit-code`), giving the healthcheck command an option to be graceful about one-time errors. I personally would not need this additional functionality but wanted to put it for a vote.

What do you think?

**Comment by djmaze** [comment] 2020-06-15 22:11
Thanks, that's an interesting idea. 

I wonder how this could be used in practice. As you said, there's a problem when using an orchestrator like swarm which tries to restart unhealthy containers. In most cases with backups that's probably not the solution to the underlying problem (which might e.g. be a full disk).

When disabling the healthcheck in swarm mode, the whole point of this being suspended. I don't think there is a way of seeing an unhealthy state without swarm restarting the container?

So in practice this might only be useful to non-swarm deployments.

**Comment by ThomDietrich** [comment] 2020-06-16 11:03
Sounds like we agree ;)

I know that you are a swarm user and in such a deployment a healthcheck based restart of the backup container does not make much sense. It would probably be best to disable the restart but still monitor the health state. I am not sure about the options you have here.

Imho it's less about the automatic reboot but about the observability.

Monitoring is my primary use case. We operate an infrastructure monitoring system (similar to Nagios) and the health state of all relevant services is a very useful property to track.

> So in practice this might only be useful to non-swarm deployments.

Imho definitely useful for direct deployments, not sure about swarm, kubernetes or similar.

What do others think? I am also interested in other implementation ideas. Who thinks "workaround 2" is meaningful?

**Comment by zoispag** [comment] 2020-06-16 11:07
I've seen one-time failures because of excess job data, that are usually short-lived and deleted after 24h, so I got out-of-memory error from restic. Usually I just ignore the error and it works during the next run. But I wouldn't think of this being a common scenario.

**Comment by djmaze** [comment] 2020-06-16 20:58
Agreeing with @zoispag that most of the errors are one-time only (e.g. because of out-of-memory errors). So workaround 2 might make sense, with the healthcheck only failing after 2 or more failures in a row. 

I think we can try that one out. But better not enable the healthcheck per default for now – in order to preserve backwards compatibility.

**Comment by ThomDietrich** [comment] 2020-06-16 21:09
Thanks @zoispag, I thought about cases like this. For such an error I'd normally expect a retry after some minutes but let's not sidetrack this.

Fine by me to go with workaround 2.

> But better not enable the healthcheck per default for now

We are once again talking about swarm deployments? Backwards compatibility is a good reason, let me see what I can do.

**Comment by djmaze** [comment] 2020-06-21 14:44
Yes, swarm deployments as well as unexpected behaviour for people who update. But on the other hand, if we make it a major release we could be safe with such changes.

**Comment by ThomDietrich** [comment] 2020-07-08 10:57
Today I ran into the issue of a locked repository. A repository being locked should also be a reason for an "unhealthy" state. Just leaving this note for reference.

**Comment by ThomDietrich** [comment] 2020-10-30 19:32
@djmaze I suggest to disable stalebot on this repo. I generally don't like the idea but he is valuable in big high-frequented projects. In this project he just closes tickets that he really shouldn't.

On another note: Sorry but I didn't find the time to work on this in the first lockdown...

**Comment by djmaze** [comment] 2020-10-31 15:08
@ThomDietrich As an (unpaid) maintainer of a few open-source projects in my spare time, I disagree. It is often hard to find time and motivation for the "gardening" of issues and pull requests. Oftentimes issues are created because of particular itches and wishes of one or a few users. 

Also, it it often not clear if an issue is still relevant or if the reported bug is still present. It feels like most of the time people do not close issues if the underlying problems are solved for them.

Considering the limited time and energy of a maintainer, it feels good to have an "assistant" which helps you keep the lists small so you can focus on the issues which people really still care about. *If* they care, they can comment and thus demonstrate that the issue is still of importance to them. I encourage everyone to do so.

Maybe it makes sense to even have this statement as a manifest in the README so everyone knows that this is meant do to good stuff™. I am open for counterarguments though.

@ThomDietrich Having said all that, I really appreciate the interest and care you showed to this project (at least until the virus took us all and made us think of different things). If you are interested, I would be happy to make you a collaborator so we share the maintenance burden (and you can have more impact). Also, we could then talk about deactivating the stale bot :)

**Comment by towo** [comment] 2020-11-13 13:55
I'm pretty much involved here, just from my personal experience with stalebot:

* I open a issue describing a bug that exists (and I don't have the time or capacity to fix)
* Maintainer utterly ignores the issue
* Stalebot closes the issue

Repository looks "issue-free", but really isn't, and even if the maintainer were to look at what bugs are still open, they'd either 

1. have to go through bugs closed by stalebot, defeating the usage entirely
2. ignore the fact that people may have reported valid issues and just couldn't be bothered to insistently keep harping on like a broken record. I personally consider that be more spammy than just having the issue in the inbox. I can't think of a single person who likes being bumped by a "reopen" comment every time the bot closes an issue.

I get that there's people abusing issues as a cheap web form to (involuntarily) annoy maintainers, but burying valid issues because a reporter doesn't want to be as annoying as a spammer is not the way to solve that problem.

**Comment by djmaze** [comment] 2020-11-14 15:40
@towo, I get your frustration and I can feel these problems as well. Also, I get that you are speaking in general terms here. But nonetheless I have to answer in context of this project.

> 2. ignore the fact that people may have reported valid issues and just couldn't be bothered to insistently keep harping on like a broken record. [...] I can't think of a single person who likes being bumped by a "reopen" comment every time the bot closes an issue.

I guess the point is people _should_ be annoyed by this and be remembered that there was an open issue, being forced to indicate that they still care. 

Oftentimes (of course I can only speak for myself) and as said above those are issues which are specific to a small part of the userbase or very specific wishes for enhancement. There is no obligation for the maintainer to deal with every of those issues. After all, this is an open source project and people are welcome to send in pull requests.

There is so much (mental) burden on being an OSS maintainer. I think it is fair to redistribute some of this to the people who are mostly *benefitting* from the work. Of course, it has to be done _right_. It should not end up as you described.

> Maintainer utterly ignores the issue

I think I made efforts to not ignore any important issues in this repo. At least I try to have a look at every issue and make sure that there is a reaction to each one. But having many other things higher on the priority list, it may happen that some crucial things are being forgotten. Also, there are issues where I am waiting on other people's actions.

I have to admit that, as far as I am concerned, this project is currently in _works for me_ mode. There are some problems, but for my use case it currently works good enough. A related problem here is that the project can be used in two modes: docker only and swarm mode. As I am personally only using swarm mode, oftentimes I didn't have a close enough look at the non swarm-mode issues. I should probably work on that. 

(I will hopefully also find time to work on two important features I have long been craving for in swarm mode – a global scheduler and a _practical_ healthcheck implementation (which might be used in normal docker mode as well).)

**Comment by towo** [comment] 2020-11-14 21:53
Just so I don't seem like a dick for being a bit ranty above: I see your point of view and get where you're coming from. Since it boils down to the persons involved and how they feel one should, or should not, act, I don't think there's any reasonable compromise in having two valid but by definition irreconceilably different approaches how to handle this behavior ­— except for seeing the person on the other side of the screen as a person. But, uh, that's just good life advice and not particularly related to the stalebot. ;)

While I'm not actively maintaining OSS, volunteer admin work for non-profits can come with similar issues of mental stress, and can only dread being that exposed to some of the more annoying and demanding folks. We've got enough burnout this year anyway.

Thanks for taking the time to just look at the argument from one of the other sides, now go on doing what keeps you actually engaged with your projects. :) :+1:

**Comment by djmaze** [comment] 2020-11-14 22:20
Thank you for the understanding response. And I might actually think about (adequate) stalebot usage in this project again :)

**Comment by ThomDietrich** [comment] 2021-02-05 18:33
Still interested in this feature, alongside the other benefits it would bring.
Sorry I don't have more to share at this point, just wanted to let you know that I am still here...

I have to apologize, I didn't expect this side comment to escalate into a lengthy discussion.

> I really appreciate the interest and care you showed to this project [...] I would be happy to make you a collaborator

It's my pleasure! Thanks for the offer. I would accept it if you were in need of a second maintainer but as long as we as a community are able to discuss and merge changes in unison, there is no need to give me more power ;) Thanks!

**Comment by varac** [comment] 2021-02-06 13:45
As a intermediate solution I'm using an adapted [script that exports prometheus metrics ](https://gist.github.com/varac/0e16de606828968b30f0cd247ed79cbc), which can get run using the `POST_COMMANDS_EXIT` argument like this:

```
---
version: "3.3"

services:
  backup:
    container_name: resticker_backup
    image: mazzolino/restic
    hostname: ...
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 38 3 * * *"
      RESTIC_REPOSITORY: 'sftp:...'
      RESTIC_PASSWORD: '...'
      RESTIC_BACKUP_SOURCES: /mnt
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: Europe/Berlin
      POST_COMMANDS_EXIT: |-
        /tmp/restic_metrics.sh
    volumes:
      - /:/mnt/:ro
      - /root/.ssh/restic_backup:/root/.ssh/id_rsa:ro
      - ./files/resticker/known_hosts:/root/.ssh/known_hosts:ro
      - ./files/resticker/ssh_config:/root/.ssh/config:ro
      - ./files/resticker/restic_metrics.sh:/tmp/restic_metrics.sh:ro
      - /var/lib/prometheus/node-exporter/restic.prom:/tmp/restic.prom
```

It will export metrics to `/var/lib/prometheus/node-exporter/restic.prom` on the docker host, where it can get picked up by the [node-exporter textfile collector](https://github.com/prometheus/node_exporter#textfile-collector).

**Closed** 2021-06-09 21:44 UTC
Labels: enhancement, wontfix
